sudo: false

language: python

python:
  - 3.5.2

install:
  - pip install codecov
  - pip install openpyxl
  - pip install typecheck-decorator

script:
  - coverage run tests.py

after_success:
  - codecov